/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "rpc.h"

bool_t
xdr_string_char (XDR *xdrs, string_char *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->s, ~0))
		 return FALSE;
	 if (!xdr_char (xdrs, &objp->c))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_string_int (XDR *xdrs, string_int *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->s, ~0))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->i))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_string_string (XDR *xdrs, string_string *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->s1, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->s2, ~0))
		 return FALSE;
	return TRUE;
}
